services:
  home:
    build: .
    container_name: govtools-home
    restart: always
    env_file:
      - .env.local
    environment:
      - PORT=3000
    expose:
      - "3000"
    volumes:
      - ..:/apps:ro

  cataloger:
    build:
      context: ../govdoc-cataloger
    container_name: govdoc-cataloger-app
    restart: always
    env_file:
      - .env.local
    environment:
      - PORT=3000
    expose:
      - "3000"

  ia-open:
    build:
      context: ../ia-open-materials
    container_name: ia-open-materials
    restart: always
    env_file:
      - .env.local
    environment:
      - PORT=3000
    expose:
      - "3000"

    volumes:
      - ia_data:/app/data

  caddy:
    image: caddy:2-alpine
    container_name: govtools-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ..:/apps # Mount parent to access other logs/json if needed
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - home
      - cataloger
      - ia-open

volumes:
  caddy_data:
  caddy_config:
  ia_data:
