import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: 'standalone',
  async rewrites() {
    return [
      // Serve the static heatmap at /erschliessung/heatmap (without .html).
      // The file lives at public/erschliessung/heatmap/index.html, regenerated
      // by Erschliessung/evaluation_runs/build_cycles_heatmap_html.py.
      { source: '/erschliessung/heatmap', destination: '/erschliessung/heatmap/index.html' },
      // Static model-consensus explorer for host classification (per-host vote
      // distributions per field), regenerated by host-classification/eval/
      // gen_consensus_html.py into public/model-evals/host-class/consensus/.
      { source: '/model-evals/host-class/consensus', destination: '/model-evals/host-class/consensus/index.html' },
    ];
  },
  async redirects() {
    return [
      // Legacy URL — anyone with the old link gets bounced to the clean URL.
      { source: '/erschliessung/heatmap.html', destination: '/erschliessung/heatmap', permanent: true },
      // Erschließung → Model Evals rename: keep old deep links working.
      { source: '/erschliessung/ant-catalog', destination: '/model-evals/ant-catalog', permanent: true },
      { source: '/erschliessung/interpolation', destination: '/model-evals/interpolation', permanent: true },
    ];
  },
};

export default nextConfig;
