// AUTO-GENERATED by evaluation_runs/ant_catalog/gen_page_data.py — do not edit by hand.
// ANT catalog-metadata model comparison. accuracy = macro mean of per-field agreement
// scores vs a frontier-consensus SILVER reference (panel gpt-4.1/opus/gemini-flash +
// grok-4 arbiter). isPanel rows are reference-defining (their accuracy is circular/inflated).
// avgFields/validOutputRate = JSON/schema validity, NOT correctness.

export type AntModelRow = {
  model: string; tier: 'hosted' | 'local'; ok: number; n: number;
  avgFields: number; avgLatencyS: number; avgPromptTok: number; avgRespTok: number;
  costPer1kDocs: number | null; accuracy: number | null; isPanel: boolean;
  validOutputRate: number | null;
};

export type AntRouting = { field: string; bestModel: string | null; accuracy: number | null };

export const ANT_RUN_META = { docs: 13, models: 27, generated: "2026-06-22", accuracyScored: true };

export const ANT_MODEL_ROWS: AntModelRow[] = [
  {
    "model": "anthropic:claude-opus-4-8",
    "tier": "hosted",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 8.3,
    "avgPromptTok": 2513,
    "avgRespTok": 689,
    "costPer1kDocs": 89.37,
    "accuracy": 0.817,
    "isPanel": true,
    "validOutputRate": null
  },
  {
    "model": "openai:gpt-4.1",
    "tier": "hosted",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 4.1,
    "avgPromptTok": 1754,
    "avgRespTok": 327,
    "costPer1kDocs": 6.12,
    "accuracy": 0.777,
    "isPanel": true,
    "validOutputRate": null
  },
  {
    "model": "gemini:2.5-flash",
    "tier": "hosted",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 7.8,
    "avgPromptTok": 1979,
    "avgRespTok": 526,
    "costPer1kDocs": 1.91,
    "accuracy": 0.769,
    "isPanel": true,
    "validOutputRate": null
  },
  {
    "model": "xai:grok-4",
    "tier": "hosted",
    "ok": 13,
    "n": 13,
    "avgFields": 10.0,
    "avgLatencyS": 6.9,
    "avgPromptTok": 1860,
    "avgRespTok": 231,
    "costPer1kDocs": 9.04,
    "accuracy": 0.739,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "anthropic:claude-sonnet-4-6",
    "tier": "hosted",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 10.6,
    "avgPromptTok": 1981,
    "avgRespTok": 588,
    "costPer1kDocs": 14.76,
    "accuracy": 0.734,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "mistral:large",
    "tier": "hosted",
    "ok": 12,
    "n": 13,
    "avgFields": 9.5,
    "avgLatencyS": 28.1,
    "avgPromptTok": 2063,
    "avgRespTok": 483,
    "costPer1kDocs": 7.02,
    "accuracy": 0.702,
    "isPanel": false,
    "validOutputRate": 1.0
  },
  {
    "model": "anthropic:claude-haiku-4-5",
    "tier": "hosted",
    "ok": 13,
    "n": 13,
    "avgFields": 10.0,
    "avgLatencyS": 4.9,
    "avgPromptTok": 1996,
    "avgRespTok": 478,
    "costPer1kDocs": 4.39,
    "accuracy": 0.651,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "openai:gpt-4o-mini",
    "tier": "hosted",
    "ok": 13,
    "n": 13,
    "avgFields": 10.0,
    "avgLatencyS": 3.0,
    "avgPromptTok": 1756,
    "avgRespTok": 182,
    "costPer1kDocs": 0.37,
    "accuracy": 0.548,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "gemini:2.5-pro",
    "tier": "hosted",
    "ok": 0,
    "n": 3,
    "avgFields": 0.0,
    "avgLatencyS": 0.0,
    "avgPromptTok": 0,
    "avgRespTok": 0,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:granite3.3-8b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 14.5,
    "avgPromptTok": 2150,
    "avgRespTok": 277,
    "costPer1kDocs": null,
    "accuracy": 0.507,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:gemma2-9b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 10.7,
    "avgPromptTok": 1974,
    "avgRespTok": 212,
    "costPer1kDocs": null,
    "accuracy": 0.489,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:qwen2.5-7b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 10.0,
    "avgPromptTok": 1965,
    "avgRespTok": 219,
    "costPer1kDocs": null,
    "accuracy": 0.456,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:apertus-8b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 17.3,
    "avgPromptTok": 2000,
    "avgRespTok": 314,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:mistral:7b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 13.6,
    "avgPromptTok": 2164,
    "avgRespTok": 278,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:qwen2.5-coder-7b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 10.4,
    "avgPromptTok": 1965,
    "avgRespTok": 228,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:gemma-sealion-27b",
    "tier": "local",
    "ok": 10,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 69.8,
    "avgPromptTok": 1988,
    "avgRespTok": 348,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:phi3-mini",
    "tier": "local",
    "ok": 9,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 6.6,
    "avgPromptTok": 2240,
    "avgRespTok": 277,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:qwen2.5-3b",
    "tier": "local",
    "ok": 9,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 5.6,
    "avgPromptTok": 1963,
    "avgRespTok": 282,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:olmo2:7b",
    "tier": "local",
    "ok": 9,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 7.6,
    "avgPromptTok": 1780,
    "avgRespTok": 141,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:eurollm-9b",
    "tier": "local",
    "ok": 8,
    "n": 10,
    "avgFields": 9.2,
    "avgLatencyS": 12.6,
    "avgPromptTok": 1625,
    "avgRespTok": 263,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:apertus-70b",
    "tier": "local",
    "ok": 8,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 357.4,
    "avgPromptTok": 1992,
    "avgRespTok": 307,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:climategpt-70b",
    "tier": "local",
    "ok": 8,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 163.9,
    "avgPromptTok": 1853,
    "avgRespTok": 356,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:llama3",
    "tier": "local",
    "ok": 6,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 7.4,
    "avgPromptTok": 2087,
    "avgRespTok": 159,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:climategpt-13b",
    "tier": "local",
    "ok": 6,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 23.9,
    "avgPromptTok": 2427,
    "avgRespTok": 175,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:apertus-70b-q3",
    "tier": "local",
    "ok": 4,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 902.8,
    "avgPromptTok": 1728,
    "avgRespTok": 178,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:climategpt-7b",
    "tier": "local",
    "ok": 3,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 7.2,
    "avgPromptTok": 2280,
    "avgRespTok": 112,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  },
  {
    "model": "ollama:deepseek-r1-8b",
    "tier": "local",
    "ok": 1,
    "n": 10,
    "avgFields": 10.0,
    "avgLatencyS": 23.8,
    "avgPromptTok": 3468,
    "avgRespTok": 499,
    "costPer1kDocs": null,
    "accuracy": null,
    "isPanel": false,
    "validOutputRate": null
  }
];

export const ANT_ROUTING: AntRouting[] = [
  {
    "field": "abstract_summary",
    "bestModel": "anthropic:claude-sonnet-4-6",
    "accuracy": 0.75
  },
  {
    "field": "coverage_codes",
    "bestModel": "anthropic:claude-sonnet-4-6",
    "accuracy": 1.0
  },
  {
    "field": "coverage_text",
    "bestModel": "xai:grok-4",
    "accuracy": 1.0
  },
  {
    "field": "document_type_code",
    "bestModel": "xai:grok-4",
    "accuracy": 1.0
  },
  {
    "field": "issuing_body_name",
    "bestModel": "anthropic:claude-haiku-4-5",
    "accuracy": 0.938
  },
  {
    "field": "jurisdiction_code",
    "bestModel": "anthropic:claude-sonnet-4-6",
    "accuracy": 1.0
  },
  {
    "field": "key_points",
    "bestModel": "openai:gpt-4o-mini",
    "accuracy": 0.2
  },
  {
    "field": "language_code",
    "bestModel": "anthropic:claude-haiku-4-5",
    "accuracy": 1.0
  },
  {
    "field": "subjects",
    "bestModel": "xai:grok-4",
    "accuracy": 0.333
  },
  {
    "field": "title",
    "bestModel": "anthropic:claude-haiku-4-5",
    "accuracy": 0.786
  }
];
