// Auto-generated by evaluation_runs/build_public_interest_passes.py.
// Do not hand-edit. Re-run after new cycles to refresh.

export type Evaluation = 'correct' | 'incorrect' | 'partial' | 'n/a';

export interface PublicInterestPassRow {
  model: string;
  modelLabel: string;
  qid: string;
  question: string;
  groundTruth: string;
  iaUrl: string | null;
  // Three response variants — one per input class. Each carries
  // its own evaluation so the cell can be tinted independently.
  pdfResponse: string;
  pdfEvaluation: Evaluation;
  jsonResponse: string;
  jsonEvaluation: Evaluation;
  cardResponse: string;
  cardEvaluation: Evaluation;
}

export const PUBLIC_INTEREST_PASSES_META = {
  cycleForCardColumn: "cycle17",
  cardVariant: "pipeline-v0.7-csv-only",
  cardMode: "M3-L4 (oracle retrieval, single pre-selected card per question)",
  cardSizeNote: "Compact CSV-format card, typically ~1.5 KB per question",
  jsonMode: "M2a (raw decompressed docling.json — the IA-default Docling derivative)",
  pdfMode: "N/A — Apertus 8B and ClimateGPT 13B are text-only and cannot ingest a PDF binary directly",
  questionCountWithAtLeastOnePass: 5,
} as const;

export const PUBLIC_INTEREST_PASSES: PublicInterestPassRow[] = [
  {
    model: "hf.co/bartowski/swiss-ai_Apertus-8B-Instruct-2509-GGUF:Q4_K_M",
    modelLabel: "Apertus 8B Instruct (Swiss AI)",
    qid: "Q-NAT-001",
    question: "Looking at the list of Physalia (Portuguese man-of-war) strandings on British and European coasts in Vol 27, what year did the first reported stranding on the Belgian coast happen, and what was the locality?",
    groundTruth: "1912, Knocke",
    iaUrl: "https://archive.org/details/marine-biological-association-uk-journal_1947-1948_27/page/n154/mode/1up",
    pdfResponse: "Text-only model \u2014 PDF must be pre-converted.",
    pdfEvaluation: "n/a",
    jsonResponse: "Context overflow \u2014 ~1 GB JSON vs 4K-8K window.",
    jsonEvaluation: "n/a",
    cardResponse: "The first reported stranding on the Belgian coast happened in 1912, with the locality being Knocke (Belgium). This information is found in the row for 1912, specifically in the \"Locality\" column.",
    cardEvaluation: "correct",
  },
  {
    model: "hf.co/mradermacher/climategpt-13b-i1-GGUF:Q4_K_M",
    modelLabel: "ClimateGPT 13B (climate-domain Llama-2)",
    qid: "Q-NAT-006",
    question: "Looking at the annual fish-catch table in Vol 27, how much less fish weight was caught in 1934 than the year before? Show both source values and the difference.",
    groundTruth: "2000 less; 1933=95000, 1934=93000",
    iaUrl: "https://archive.org/details/marine-biological-association-uk-journal_1947-1948_27/page/n355/mode/1up",
    pdfResponse: "Text-only model \u2014 PDF must be pre-converted.",
    pdfEvaluation: "n/a",
    jsonResponse: "Context overflow \u2014 ~1 GB JSON vs 4K-8K window.",
    jsonEvaluation: "n/a",
    cardResponse: "Source:\n1934: 93,000 tons\n1933: 95,000 tons\nDifference: 2,000 tons less",
    cardEvaluation: "correct",
  },
  {
    model: "hf.co/bartowski/swiss-ai_Apertus-8B-Instruct-2509-GGUF:Q4_K_M",
    modelLabel: "Apertus 8B Instruct (Swiss AI)",
    qid: "Q-NAT-INT-001",
    question: "In Vol 27, Table III lists the organic phosphorus concentration in offshore water 3 miles south of the Eddystone Lighthouse on 23 July 1947. The table reports depths at 30 metres and 40 metres but does not include a 35-metre row. What would you estimate the organic phosphorus concentration was at 35 metres? Show the bracketing values and your interpolation method.",
    groundTruth: "5.25 (band A 5.1-5.3, band B 4.4-6.1)",
    iaUrl: "https://archive.org/details/marine-biological-association-uk-journal_1947-1948_27/page/n378/mode/1up",
    pdfResponse: "Text-only model \u2014 PDF must be pre-converted.",
    pdfEvaluation: "n/a",
    jsonResponse: "Context overflow \u2014 ~1 GB JSON vs 4K-8K window.",
    jsonEvaluation: "n/a",
    cardResponse: "Based on the provided data, I will interpolate between the depths of 30 meters (6.1 mg P/m\u00b3) and 40 meters (4.4 mg P/m\u00b3). The organic phosphorus concentration at 35 meters would be estimated as approximately **5.2 mg P/m\u00b3**. This estimate is based on linear interpolation, considering the change in concentration between these two depths.",
    cardEvaluation: "correct",
  },
  {
    model: "hf.co/bartowski/swiss-ai_Apertus-8B-Instruct-2509-GGUF:Q4_K_M",
    modelLabel: "Apertus 8B Instruct (Swiss AI)",
    qid: "Q-V27-NEG-001",
    question: "In the Vol 27 list of Physalia (Portuguese man-of-war) strandings on British and European coasts, was there a stranding reported on the coast of Greece? If so, what year and where?",
    groundTruth: "Not in source \u2014 list contains no Greek-coast entries.",
    iaUrl: "https://archive.org/details/marine-biological-association-uk-journal_1947-1948_27/page/n154/mode/1up",
    pdfResponse: "Text-only model \u2014 PDF must be pre-converted.",
    pdfEvaluation: "n/a",
    jsonResponse: "Context overflow \u2014 ~1 GB JSON vs 4K-8K window.",
    jsonEvaluation: "n/a",
    cardResponse: "No, there is no record of a Physalia (Portuguese man-of-war) stranding on the coast of Greece in this list. The closest location mentioned is \"Gu\u00e9ethary Bantry, Co. Cork\" in Ireland and \"Tragumina, Co, Cork\" also in Ireland.",
    cardEvaluation: "correct",
  },
  {
    model: "hf.co/mradermacher/climategpt-13b-i1-GGUF:Q4_K_M",
    modelLabel: "ClimateGPT 13B (climate-domain Llama-2)",
    qid: "Q-V27-NEG-001",
    question: "In the Vol 27 list of Physalia (Portuguese man-of-war) strandings on British and European coasts, was there a stranding reported on the coast of Greece? If so, what year and where?",
    groundTruth: "Not in source \u2014 list contains no Greek-coast entries.",
    iaUrl: "https://archive.org/details/marine-biological-association-uk-journal_1947-1948_27/page/n154/mode/1up",
    pdfResponse: "Text-only model \u2014 PDF must be pre-converted.",
    pdfEvaluation: "n/a",
    jsonResponse: "Context overflow \u2014 ~1 GB JSON vs 4K-8K window.",
    jsonEvaluation: "n/a",
    cardResponse: "No. There were no Physalia strandings reported on the coast of Greece.",
    cardEvaluation: "correct",
  },
  {
    model: "hf.co/bartowski/swiss-ai_Apertus-8B-Instruct-2509-GGUF:Q4_K_M",
    modelLabel: "Apertus 8B Instruct (Swiss AI)",
    qid: "Q-NOAA-NEG-001",
    question: "How many cruises were conducted in 1948 according to the California Current fisheries database?",
    groundTruth: "Not in source \u2014 the database starts in 1950.",
    iaUrl: null,
    pdfResponse: "Text-only model \u2014 PDF must be pre-converted.",
    pdfEvaluation: "n/a",
    jsonResponse: "Context overflow \u2014 ~1 GB JSON vs 4K-8K window.",
    jsonEvaluation: "n/a",
    cardResponse: "There is no information about cruise numbers for 1948 in the provided table or source material. The earliest year mentioned is 1950 (Cruise Number 50Y01). Therefore, it's not possible to determine how many cruises were conducted in 1948 based on this data.",
    cardEvaluation: "correct",
  },
];
